import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {JSDOM} from 'jsdom';
const w=new JSDOM('<div id="host"></div><video id="video"></video><script src="http://localhost/static/episode-viewer.js"></script>',{runScripts:'outside-only',pretendToBeVisual:true,url:'http://localhost/'}).window;
Object.defineProperty(w.document,'currentScript',{get:()=>w.document.querySelector('script')});
w.ResizeObserver=class {observe(){}disconnect(){}};w.AbortSignal.timeout=()=>undefined;
const video=w.document.querySelector('video');
Object.defineProperties(video,{readyState:{get:()=>2},videoWidth:{get:()=>0},videoHeight:{get:()=>0}});
video.pause=()=>{};video.load=()=>{};
let onFrame;video.requestVideoFrameCallback=callback=>{onFrame=callback;return 1;};video.cancelVideoFrameCallback=()=>{};
const pose=n=>({joints:[n],root:[99,88,77,1,0,0,0]});
const actual0=pose(.1),actual1=pose(.6),prediction0=pose(.2),prediction1=pose(.7),demo0=pose(.3);
let data={robot:'skynet_shadow_right',joint_names:['h_rh_FFJ1'],frames:[{time:0,hand_poses:{actual:actual0,prediction:prediction0,demonstration:demo0}},{time:1,hand_poses:{actual:actual1,prediction:prediction1}}],views:[]};
const hand={key:'shadow',name:'Shadow',floating_hand:{palm:'{s}h_palm'}};
w.fetch=async url=>({ok:true,json:async()=>url==='/api/hands'?{hands:[hand]}:url.endsWith('/model')?{urdf_url:'/hand.urdf',joints:[],mesh_count:12}:{state:'READY',viewer:data}});
let finishLoad;const models=[];
w.TestHandsViewer=class {constructor(){this.poses=[];models.push(this);}load(){return new Promise(resolve=>{finishLoad=resolve;});}configurePlayback(options){this.options=options;}setFingerPose(p){this.poses.push(p);return Boolean(p);}dispose(){this.disposed=true;}};
const source=await readFile(new URL('../static/episode-viewer.js',import.meta.url),'utf8');
const script=source.replace(/await import\(\s*document.querySelector\('meta\[name="hand-viewer-module"\]'\)[\s\S]*?\n\s*\)/,'({HandsViewer:window.TestHandsViewer})');
assert.notEqual(source,script,'replace only the WebGL module import');w.eval(script);
const flush=async()=>{for(let i=0;i<5;i++)await new Promise(r=>setImmediate(r));};
try{
 const viewer=w.SkynetEpisodeViewer.open('host','video','/rollout');await flush();
 video.currentTime=1;onFrame(0,{mediaTime:0});
 finishLoad(true);await flush();const model=models[0];
 assert.equal(model.options.palm,'rh_palm');assert.equal(model.poses.at(-1),actual0,'late model load uses the decoded video frame');
 assert.equal(viewer.handPoseSelect.value,'actual');
 onFrame(0,{mediaTime:1});assert.equal(model.poses.at(-1),actual1,'video frames update finger poses');
 viewer.handPoseSelect.value='prediction';viewer.handPoseSelect.dispatchEvent(new w.Event('change'));
 assert.equal(model.poses.at(-1),prediction1,'prediction uses its own pose');
 viewer.handPoseSelect.value='demonstration';viewer.handPoseSelect.dispatchEvent(new w.Event('change'));
 assert.equal(model.poses.at(-1),undefined,'expired demonstration requests the default hand pose');
 assert.equal(viewer.handPoseStatus.textContent,'Default pose');
 viewer.seek.dispatchEvent(new w.Event('pointerdown'));viewer.seek.value='0';viewer.seek.dispatchEvent(new w.Event('input'));
 assert.equal(model.poses.at(-1),demo0,'scrubbing follows the requested frame immediately');
 viewer.seek.dispatchEvent(new w.Event('pointerup'));
 viewer.view='interactive';viewer.handPoseSelect.value='actual';viewer.handPoseSelect.dispatchEvent(new w.Event('change'));
 viewer.next.click();assert.equal(model.poses.at(-1),actual1,'next frame moves the sidebar');
 viewer.previous.click();assert.equal(model.poses.at(-1),actual0,'previous frame moves the sidebar');
 viewer.data={...data,frames:[{time:0,hand_poses:{demonstration:demo0}}]};viewer.draw();
 assert.equal(viewer.handPoseSelect.value,'demonstration','legacy rollout selects and labels the only recorded pose');
 viewer.data={...data,frames:[{time:0}]};viewer.draw();assert.equal(model.poses.at(-1),null,'missing joint data requests the default hand pose');
 assert.equal(viewer.handPoseSelect.disabled,true);
 assert.equal(viewer.handPoseSelect.parentElement.hidden,true,'hide the pose selector when only a static model is available');
 assert.equal(viewer.handPoseStatus.textContent,'Default pose');
 data={...data,frames:[{time:0,hand_poses:{actual:actual0}},{time:1,hand_poses:{actual:actual1}}]};
 viewer.load('/recording',{collection:true});await flush();finishLoad(true);await flush();
 assert.equal(viewer.handPoseSelect.parentElement.hidden,true,'collection has one pose and no unnecessary selector');
 viewer.view='interactive';viewer.next.click();assert.equal(models.at(-1).poses.at(-1),actual1);
 viewer.load('/late',{collection:true});await flush();const late=models.at(-1);viewer.close();finishLoad(true);await flush();
 assert.equal(late.disposed,true);assert.equal(late.poses.length,0,'late completion cannot animate a closed viewer');
 console.log('Sidebar hand sync: decoded frames, late loading, layer selection, expiry, scrubbing, step controls, recordings and cleanup passed.');
}finally{w.SkynetEpisodeViewer.close('host');w.close();}
