import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {JSDOM} from 'jsdom';
const w=new JSDOM(await readFile(new URL('../static/index.html',import.meta.url),'utf8'),{url:'http://localhost:8080/?data_view=recording#data',runScripts:'outside-only'}).window;
const el=id=>w.document.getElementById(id);
let reviewed,converted,linked,navigation,changes=0,registryState='ready';
w.openLiveReview=s=>reviewed=s.id;
w.openPolicyExport=id=>converted=id;
w.showRecordingResources=id=>linked=id;
w.activateTab=(...args)=>navigation=args;
w.formatDate=value=>value;
w.recordingRegistrationSummary=id=>({state:registryState,count:id==='one'?2:0});
w.document.addEventListener('collection-recordings-changed',()=>changes++);
try {
 w.eval(await readFile(new URL('../static/live-conversion.js',import.meta.url),'utf8'));
 const one={id:'one',profile:{task:'cube',robot:'Shadow'},created_at:'2026-09-08',recordings:['a','b'],archive:{state:'READY'}};
 const two={...one,id:'two',profile:{task:'stick',robot:'Shadow'},recordings:['c']};
 w.renderSimulationRecordings([one,two]);w.renderSimulationRecordings([one,two]);
 assert.equal(changes,1);
 let rows=el('simulation-recordings-body').rows;
 assert.equal(rows[0].cells.length,5);
 assert.equal(rows[0].cells[3].textContent,'2 datasets');
 assert.equal(rows[1].cells[3].textContent,'0 datasets');
 assert.equal(rows[0].cells[3].querySelector('.state-pill'),null);
 assert.doesNotMatch(el('simulation-recordings-body').textContent,/Stored on sky2/);
 rows[0].cells[3].querySelector('button').click();assert.equal(linked,'one');
 const buttons=rows[0].querySelectorAll('.row-actions button');buttons[0].click();buttons[1].click();
 assert.equal(reviewed,'one');assert.equal(converted,'one');
 el('new-recording').click();assert.deepEqual(navigation,['data',true,'collect']);
 w.filterSimulationRecordings(['two'],'Only stick');
 assert.equal(el('simulation-recordings-body').rows.length,1);assert.equal(el('simulation-recordings-body').rows[0].dataset.sessionId,'two');
 w.renderSimulationRecordings([one,two]);assert.equal(el('simulation-recordings-body').rows.length,1,'refresh retains exact dataset filter');
 el('simulation-recordings-search').value='cube';el('simulation-recordings-search').dispatchEvent(new w.Event('input'));
 assert.equal(el('simulation-recordings-body').rows[0].dataset.sessionId,'one','typing replaces dataset filter');
 registryState='unavailable';w.document.dispatchEvent(new w.Event('recording-registry-changed'));
 assert.equal(el('simulation-recordings-body').rows[0].cells[3].textContent,'—','failed catalog must not claim zero datasets');
 w.filterSimulationRecordings([],'External dataset');assert.equal(el('simulation-recordings-body').rows[0].cells[0].colSpan,5);
 console.log('Recordings: dataset counts, navigation, multi-recording filters, refresh and unavailable state passed.');
} finally {w.close();}
