import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {JSDOM} from "jsdom";
const w = new JSDOM(await readFile(new URL("../static/index.html", import.meta.url), "utf8"), {runScripts:"outside-only", url:"http://skynet/#settings"}).window;
const el = id => w.document.getElementById(id);
w.HTMLDialogElement.prototype.showModal = function(){this.open=true;};
w.HTMLDialogElement.prototype.close = function(){this.open=false;this.dispatchEvent(new w.Event("close"));};
w.escapeHtml = text => String(text).replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll('"', "&quot;");
w.closeActiveDisclosure = ()=>{};
const refresh=[];
w.loadExperiments=w.loadRuns=w.loadEvaluations=async()=>{refresh.push(1);};
w.showToast = ()=>{};
const flush = async()=>{for(let i=0;i<6;i++)await new Promise(r=>setImmediate(r));};
let calls=[], handler;
w.api = (url, options={})=>{calls.push({url,...options});return handler(url, options);};
for (const file of ["dialogs.js","maintenance.js"]) w.eval(await readFile(new URL("../static/"+file, import.meta.url), "utf8"));
const launch=w.document.createElement("button");launch.dataset.deleteKind="run";launch.dataset.deleteId="run";w.document.body.append(launch);
try {
 handler=async()=>({label:"Run",token:"a".repeat(64),blockers:[{id:"eval",kind:"evaluation",label:"<unsafe>",reason:"Delete evaluation first"}],counts:{runs:1},files:[]});
 launch.click();await flush();
 assert.equal(el("maintenance-confirm").disabled,true);
 assert.match(el("maintenance-content").textContent,/<unsafe>/);
 assert.equal(el("maintenance-content").querySelector("unsafe"),null);
 handler=async()=>({label:"Evaluation",token:"b".repeat(64),blockers:[],counts:{evaluations:1,evaluation_episodes:1},files:[]});
 el("maintenance-content").querySelector("button").click();await flush();
 assert.equal(el("maintenance-confirm").disabled,false);
 let finish;
 handler=()=>new Promise(resolve=>{finish=resolve;});
 el("maintenance-confirm").click();el("maintenance-confirm").click();
 assert.equal(calls.filter(c=>c.method==="DELETE").length,1,"double clicks submit once");
 w.document.dispatchEvent(new w.KeyboardEvent("keydown",{key:"Escape",bubbles:true}));
 assert.equal(el("maintenance-dialog").open,true,"deletion stays visible until completion");
 finish({deleted:true});await flush();
 assert.equal(refresh.length,3,"all related histories refresh");
 assert.equal(el("maintenance-dialog").open,false);
 handler=async()=>({root:"/cluster",token:"c".repeat(64),items:[{path:"/cluster/tmp",selectable:true,size_bytes:10,reason:"Unreferenced"},{path:"/cluster/new",selectable:false,size_bytes:12,reason:"Recent"}],pending_deletions:[]});
 el("inspect-cluster-storage").click();await flush();
 assert.equal(el("maintenance-confirm").disabled,true,"no default destructive selection");
 const check=el("maintenance-content").querySelector("input");check.click();
 assert.equal(el("maintenance-confirm").disabled,false);
 assert.equal(el("maintenance-content").querySelectorAll("input")[1].disabled,true);
 handler=async()=>{throw Error("Storage changed");};
 el("maintenance-confirm").click();await flush();
 assert.match(el("maintenance-message").textContent,/Storage changed/);
 assert.equal(el("maintenance-confirm").disabled,true,"stale plan cannot be re-submitted");
 el("maintenance-dialog").querySelector("[data-dialog-close]").click();
 assert.equal(el("maintenance-dialog").open,false);
 console.log("Deletion UI: dependency guidance, escaping, double clicks, refresh, safe selection and stale-plan handling passed.");
} finally {w.close();}
