import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {JSDOM} from 'jsdom';
const w = new JSDOM(await readFile(new URL('../static/index.html',import.meta.url),'utf8'),{runScripts:'outside-only',pretendToBeVisual:true,url:'http://localhost:8080/#cluster'}).window;
const el=id=>w.document.getElementById(id);
const observers=[];
const NativeObserver=w.MutationObserver;
w.MutationObserver=class extends NativeObserver {constructor(callback){super(callback);observers.push(this);}};
w.fetch=()=>new Promise(()=>{});
const scrolls=[];
w.scrollTo=()=>{};
w.HTMLElement.prototype.scrollIntoView=function(options){scrolls.push({target:this,options});};
const frame=()=>new Promise(resolve=>w.requestAnimationFrame(resolve));
w.matchMedia=()=>({matches:false,addEventListener(){},removeEventListener(){}});
w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};
w.HTMLDialogElement.prototype.close=function(value=''){if(this.open){this.returnValue=value;this.open=false;this.dispatchEvent(new w.Event('close'));}};
const key=(target,key)=>target.dispatchEvent(new w.KeyboardEvent('keydown',{key,bubbles:true,cancelable:true}));
try {
  for(const file of ['dialogs.js','workspace-navigation.js','connection-settings.js','app.js']) w.eval(await readFile(new URL('../static/'+file,import.meta.url),'utf8'));
  const tabs=[...w.document.querySelectorAll('.tab-nav [role="tab"]')];
  assert.equal(tabs.filter(t=>t.tabIndex===0).length,1);
  tabs[0].focus();key(tabs[0],'ArrowRight');
  assert.equal(w.document.activeElement,tabs[1]);assert.equal(tabs[1].getAttribute('aria-selected'),'true');
  assert.equal(tabs.filter(t=>t.tabIndex===0).length,1);
  key(tabs[1],'End');assert.equal(w.document.activeElement,tabs.at(-1));
  key(tabs.at(-1),'ArrowRight');assert.equal(w.document.activeElement,tabs[0]);
  key(tabs[0],'ArrowLeft');assert.equal(w.document.activeElement,tabs.at(-1));
  key(tabs.at(-1),'Home');assert.equal(w.document.activeElement,tabs[0]);
  w.activateTab('data');const data=el('data-tab-collect');data.focus();key(data,'ArrowRight');
  assert.equal(w.document.activeElement,el('data-tab-recording'));
  w.activateTab('evaluations');
  const scroller=w.document.createElement('div');scroller.className='table-scroll';
  scroller.innerHTML='<table><tbody><tr><td>Record</td><td><button>Results</button></td></tr></tbody></table>';
  const host=w.document.createElement('section');host.className='table-panel';host.append(scroller);el('evaluations').append(host);
  const launcher=scroller.querySelector('button');
  const panel=el('evaluation-detail');
  w.toggleDisclosure(panel,'evaluation:test',launcher,{rowOwned:true});
  w.revealPanel(panel,{launcher,focusTarget:el('evaluation-detail-title'),scroll:false});
  assert.equal(panel.previousElementSibling,scroller,'Details are outside the horizontally scrolled table');
  assert.equal(panel.closest('tbody'),null);
  scroller.scrollLeft=1000;
  assert.equal(panel.closest('.table-scroll'),null,'Table panning cannot move detail heading/close offscreen');
  await frame();
  assert.equal(scrolls.findLast(entry=>entry.target===panel)?.options.block,'start','Opening detached details reveals their heading even for formerly inline callers');
  assert.equal(w.document.activeElement,el('evaluation-detail-title'));
  w.closeActiveDisclosure();
  await frame();
  assert.equal(scrolls.findLast(entry=>entry.target===launcher)?.options.block,'center','Closing returns the originating row to view');
  assert.equal(w.document.activeElement,launcher);
  w.toggleDisclosure(panel,'evaluation:test',launcher,{rowOwned:true});
  w.revealPanel(panel,{launcher,scroll:false});
  const modal=el('evaluation-rollout-dialog');
  w.SkynetDialog.open(modal,{launcher});
  key(modal,'Escape');
  assert.equal(modal.open,false,'Escape closes the active modal');
  assert.equal(panel.hidden,false,'Escape preserves its parent Results');
  w.SkynetDialog.open(modal,{launcher});
  const video=el('evaluation-rollout-video');
  let fullscreen=video,webkitFullscreen=null,nativeFullscreen=false,now=0,exitRequests=0;
  Object.defineProperty(w.document,'fullscreenElement',{configurable:true,get:()=>fullscreen});
  Object.defineProperty(w.document,'webkitFullscreenElement',{configurable:true,get:()=>webkitFullscreen});
  Object.defineProperty(video,'webkitDisplayingFullscreen',{configurable:true,get:()=>nativeFullscreen});
  w.performance.now=()=>now;
  w.document.exitFullscreen=function(){
    assert.equal(this,w.document);exitRequests++;fullscreen=null;
    w.document.dispatchEvent(new w.Event('fullscreenchange'));
    return Promise.resolve();
  };
  w.document.dispatchEvent(new w.Event('fullscreenchange'));
  key(modal,'Escape');assert.equal(exitRequests,1,'Escape explicitly exits active standard fullscreen');
  assert.equal(fullscreen,null);assert.equal(modal.open,true,'Fullscreen owns Escape');
  key(modal,'Escape');assert.equal(modal.open,true,'Fullscreen-exit key does not also close dialog');
  assert.equal(exitRequests,1,'The exit grace period does not issue another exit request');
  const cancel=new w.Event('cancel',{cancelable:true});modal.dispatchEvent(cancel);assert.equal(cancel.defaultPrevented,true);
  now=500;key(modal,'Escape');assert.equal(modal.open,false);assert.equal(panel.hidden,false);

  now=1000;w.SkynetDialog.open(modal,{launcher});webkitFullscreen=video;
  w.document.webkitExitFullscreen=function(){
    assert.equal(this,w.document);exitRequests++;webkitFullscreen=null;
    w.document.dispatchEvent(new w.Event('webkitfullscreenchange'));
  };
  w.document.dispatchEvent(new w.Event('webkitfullscreenchange'));
  key(modal,'Escape');assert.equal(exitRequests,2,'Escape exits prefixed document fullscreen');
  assert.equal(webkitFullscreen,null);assert.equal(modal.open,true);assert.equal(panel.hidden,false);

  now=1500;nativeFullscreen=true;
  video.webkitExitFullscreen=function(){
    assert.equal(this,video);exitRequests++;nativeFullscreen=false;
    video.dispatchEvent(new w.Event('webkitendfullscreen'));
  };
  video.dispatchEvent(new w.Event('webkitbeginfullscreen'));
  key(modal,'Escape');assert.equal(exitRequests,3,'Escape exits native WebKit video fullscreen');
  assert.equal(nativeFullscreen,false);assert.equal(modal.open,true);assert.equal(panel.hidden,false);
  key(modal,'Escape');assert.equal(modal.open,true,'Native fullscreen exit also preserves the modal during its exit event');
  now=2000;key(modal,'Escape');assert.equal(modal.open,false);

  now=2500;w.SkynetDialog.open(modal,{launcher});fullscreen=video;
  w.document.dispatchEvent(new w.Event('fullscreenchange'));
  w.document.exitFullscreen=()=>Promise.reject(new Error('Browser exit unavailable'));
  const rejectedEscape=new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true});
  modal.dispatchEvent(rejectedEscape);await Promise.resolve();
  assert.equal(rejectedEscape.defaultPrevented,false,'A rejected explicit exit keeps the browser Escape fallback available');
  assert.equal(modal.open,true);assert.equal(panel.hidden,false);
  delete w.document.exitFullscreen;
  const unsupportedEscape=new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true});
  modal.dispatchEvent(unsupportedEscape);
  assert.equal(unsupportedEscape.defaultPrevented,false,'Unsupported exit APIs keep native Escape available');
  assert.equal(modal.open,true);
  fullscreen=null;w.document.dispatchEvent(new w.Event('fullscreenchange'));
  now=3000;key(modal,'Escape');assert.equal(modal.open,false);assert.equal(panel.hidden,false);
  const detached=w.document.createElement('aside');detached.hidden=false;host.append(detached);
  const request=w.disclosureToken(detached);w.hideRevealedPanel(detached,null,{restoreFocus:false});
  assert.equal(w.disclosureTokenIsCurrent(detached,request),false,'Closing an untracked panel invalidates pending response');
  w.unmountRowDisclosure(panel);assert.ok(panel.isConnected);assert.equal(panel.classList.contains('row-disclosure-detached'),false);
  w.mountRowDisclosure(panel,launcher);scroller.querySelector('tbody').replaceChildren();
  assert.ok(panel.isConnected,'Refreshing rows cannot remove an expanded form or detail');
  await frame();
  console.log('Shared UI: primary/secondary tab keys, independent detail layout, top-layer Escape/fullscreen, stale close guards passed.');
} finally {for(const observer of observers)observer.disconnect();w.close();}
