import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { JSDOM } from "jsdom";
const w = new JSDOM(await readFile(new URL("../static/index.html", import.meta.url), "utf8"),
  { runScripts: "outside-only", url: "http://skynet/#settings" }).window;
const el = id => w.document.getElementById(id);
const flush = async () => { for (let i=0;i<4;i++) await new Promise(r=>setImmediate(r)); };
const calls=[];
let handler;
w.api = async (path, options={}) => { calls.push({path,...options}); return handler(path,options); };
w.eval(await readFile(new URL("../static/workspace-storage.js", import.meta.url), "utf8"));
try {
  const form=el("workspace-storage-form"), path=el("workspace-base-path");
  w.renderWorkspaceStorage({work_root:null, configured:false});
  assert.equal(path.value, "");
  assert.equal(path.disabled, false);
  assert.equal(w.SkynetStorageConfigured,false);
  assert.equal(el("save-workspace-storage").disabled,true);
  assert.equal(el("init-workspace"),null,"one atomic setup action");
  path.value="/team/alice";
  path.dispatchEvent(new w.Event("input"));
  w.renderWorkspaceStorage({work_root:null,configured:false});
  assert.equal(path.value,"/team/alice","refresh retains draft");
  let resolve;
  handler=()=>new Promise(r=>resolve=r);
  form.dispatchEvent(new w.Event("submit",{cancelable:true}));
  form.dispatchEvent(new w.Event("submit",{cancelable:true}));
  assert.equal(calls.length,1);
  assert.equal(JSON.parse(calls[0].body).expected_work_root,null);
  assert.equal(path.disabled,true);
  assert.equal(w.SkynetStorageConfigured,false,"setup remains required until success");
  resolve({work_root:"/team/alice",configured:true,gateway:"sky2"});
  await flush();
  assert.equal(w.SkynetStorageConfigured,true);
  assert.equal(el("save-workspace-storage").disabled,true);
  assert.equal(el("workspace-storage-status").textContent,"Ready");
  path.value="/occupied"; path.dispatchEvent(new w.Event("input"));
  handler=async()=>{throw Error("Base path is not empty");};
  form.dispatchEvent(new w.Event("submit",{cancelable:true})); await flush();
  assert.match(el("workspace-storage-detail").textContent,/not empty/);
  assert.equal(path.value,"/occupied");
  assert.equal(w.SkynetStorageConfigured,true,"failed replacement retains saved root");
  assert.equal(el("save-workspace-storage").disabled,false);
  assert.equal(w.localStorage.length,0);
  console.log("Storage: empty initial state, atomic setup, duplicate prevention, drafts and errors passed.");
} finally {w.close();}
